services:
  app:
    image: alfinauzikri/frankenslims:latest
    ports:
      - "8888:80"
    volumes:
      - ./app:/app

  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_DATABASE: slims
      MYSQL_USER: slims
      MYSQL_PASSWORD: slims
      MYSQL_ROOT_PASSWORD: slims
    volumes:
      - dbslims:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    profiles:
      - tools
    ports:
      - "8889:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: slims
      UPLOAD_LIMIT: 200M
      PHP_UPLOAD_MAX_FILESIZE: 200M
      PHP_POST_MAX_SIZE: 200M
    depends_on:
      - db

volumes:
  dbslims:
