services:
  app:
    image: alfinauzikri/frankenslims:latest
    ports:
      - "80"
    volumes:
      - ./app:/app

  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - dbslims:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    profiles:
      - tools
    ports:
      - "80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 200M
      PHP_UPLOAD_MAX_FILESIZE: 200M
      PHP_POST_MAX_SIZE: 200M
    depends_on:
      - db

volumes:
  dbslims:
